name: Tests
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27c

    - name: Install dependencies
      run: |
        sudo apt-get install -y build-essential pipx python3-venv pkg-config cmake docbook2x \
        python3-pip pipx
        pipx ensurepath
        pipx install meson==0.61
        pipx install ninja
        
    - name: Test build
      run: |
        sed -i "s|android-ndk-r27c|$ANDROID_NDK_HOME|g" aarch64-android-api30.txt

        meson setup build -Dprefix=/data/share -Dinit-script=sysvinit -Druntime-path=/data/local/tmp \
        -Dstrip=true -Dd_lto=true -Dlog-path=/data/share/var/log/lxc -Ddata-path=/data/share/lib/lxc \
        --localstatedir=/data/share/var -Db_pie=false -Dmemfd-rexec=false --buildtype release \
        -Dcapabilities=false -Dseccomp=false -Dselinux=false -Dapparmor=false -Dopenssl=false \
        -Ddbus=false --cross-file aarch64-android-ndk30.txt
        
        meson compile -C build
