name: Tests
on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build test
    steps:
    - uses: actions/checkout@v4

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27c

    - name: Install dependencies
      run: |
        sudo apt-get install -y -qq build-essential pipx python3-venv pkg-config cmake docbook2x \
        python3-pip pipx
        pipx ensurepath
        pipx install meson==0.61
        pipx install ninja
        
    - name: Test build
      run: |
        sed -i "s|android-ndk-r27c|$ANDROID_NDK_HOME|g" aarch64-android-api30.txt

        meson setup build \
            -Dprefix=/data/share \
            -Dinit-script=module \
            -Druntime-path=/data/share/tmp \
            -Dstrip=true \
            -Dd_lto=true \
            -Db_pie=false \
            -Dlog-path=log/lxc \
            -Ddata-path=lib/lxc \
            --localstatedir=/data/share/var \
            -Dmemfd-rexec=true \
            --buildtype debug \
            -Dcapabilities=false \
            -Dseccomp=false \
            -Dselinux=false \
            -Dapparmor=false \
            -Dopenssl=false \
            -Ddbus=false \
            -Dandroid-log=true \
            -Dlandlock-monitor=true \
            --cross-file aarch64-android-api30.txt

        meson compile -C build
        sudo /usr/local/bin/ninja -C build install

    - name: Upload artifacts lxc
      uses: actions/upload-artifact@v4.3.1
      with:
        name: android-aarch64-lxc-shared-api30
        path: /data/share/*

    - name: Upload artifacts lxc-module
      uses: actions/upload-artifact@v4.3.1
      with:
        name: android-lxc-module
        path: lxc-module.zip
