name: Sync Fork

on:
  schedule:
    - cron: '20 3 * * 1,5' # every  12:00
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: Container-On-Android
          base: main
          head: main
          pr_title: "Merge upstream branch 'main'"
          pr_message: "Merge branch 'lxc:main' into main"
          auto_merge: false
